### PR TITLE
Added Multi-Channel Support via txt file and updated README

### PR DESCRIPTION
**Pull request by Legoluke01**
- Multi-channel support was added via another txt file
- - Added a check to make sure users are inputting actual integer channel IDs, if they don't get converted into an int, the script will use the backup channel.
- Updated README.md with more instructions on how to use the mutli-channel function.
- Added start.bat for windows users.

### CODE REVIEW

**Comment by 6A31** [comment]
Good work ;)

Is there a way you can toggle multiple channels? like add another value that can be changed from False to True, so people who don't want multiple channels can still run it like normal?

**Comment by Legoluke01** [comment]
That's already possible. On the start portion of the script, I added something that would convert the channel id to an int rather than a string, if it succeeds, well, no harm done, if it doesn't, then it'll fallback to the backup channel defined in main.py. An empty channel.txt will result in strings of "", which can't be converted into integers, so it'll go to the fallback.

**Comment by 6A31** [comment]
Alright, sorry for the long response time, ;) merging...

**Comment by 6A31** [comment]
Closing due to outdated code on my side and updates on dankmemers side. Sorry for the lost effort. 

The concept was great and working. 👍

**Pull request closed without merging**
